/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 34c24ea56bcb2e4a72f2080f6f8369f4)
interface __BaseEnv_Env {
	DB: D1Database;
	ASSETS: Fetcher;
	ADMIN_USER_IDS: "";
	MODERATOR_USER_IDS: "";
	APPROVAL_THRESHOLD: "2";
	CHAT_ROOMS: DurableObjectNamespace<import("./worker").ChatRoom>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./worker");
		durableNamespaces: "ChatRoom";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "ADMIN_USER_IDS" | "MODERATOR_USER_IDS" | "APPROVAL_THRESHOLD">> {}
}
